/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora.codigo;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class TelaCalc extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalc
     */
    public TelaCalc() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    String BarraRes = "";
    String Atual = "";
    String vetor[] = new String[16];
    boolean ponto = false;
    int indice = 0;
    float resultado = 0;
    int ContCaracAtual = 0;
    int ContCaracTotal = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonResultado2 = new javax.swing.JButton();
        jTextFieldResultado = new javax.swing.JTextField();
        jButton02 = new javax.swing.JButton();
        jButton01 = new javax.swing.JButton();
        jButton03 = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonResultado = new javax.swing.JButton();
        jButton04 = new javax.swing.JButton();
        jButton05 = new javax.swing.JButton();
        jButton06 = new javax.swing.JButton();
        jButtonSoma = new javax.swing.JButton();
        jButtonVezes = new javax.swing.JButton();
        jButton08 = new javax.swing.JButton();
        jButton07 = new javax.swing.JButton();
        jButton09 = new javax.swing.JButton();
        jButtonMenos = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButton00 = new javax.swing.JButton();
        jButtonPonto = new javax.swing.JButton();
        jButtonDiv1 = new javax.swing.JButton();
        jButtonPotencia = new javax.swing.JButton();
        jButtonRaiz = new javax.swing.JButton();
        jButtonAbreParenteses = new javax.swing.JButton();
        jButtonFechaParenteses = new javax.swing.JButton();

        jButtonResultado2.setText("=");
        jButtonResultado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultado2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jTextFieldResultado.setEditable(false);
        jTextFieldResultado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldResultadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldResultadoKeyTyped(evt);
            }
        });

        jButton02.setText("2");
        jButton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton02ActionPerformed(evt);
            }
        });

        jButton01.setText("1");
        jButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton01ActionPerformed(evt);
            }
        });

        jButton03.setText("3");
        jButton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton03ActionPerformed(evt);
            }
        });

        jButtonApagar.setText("<-");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });

        jButtonResultado.setText("=");
        jButtonResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultadoActionPerformed(evt);
            }
        });

        jButton04.setText("4");
        jButton04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton04ActionPerformed(evt);
            }
        });

        jButton05.setText("5");
        jButton05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton05ActionPerformed(evt);
            }
        });

        jButton06.setText("6");
        jButton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton06ActionPerformed(evt);
            }
        });

        jButtonSoma.setText("+");
        jButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomaActionPerformed(evt);
            }
        });

        jButtonVezes.setText("x");
        jButtonVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVezesActionPerformed(evt);
            }
        });

        jButton08.setText("8");
        jButton08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton08ActionPerformed(evt);
            }
        });

        jButton07.setText("7");
        jButton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton07ActionPerformed(evt);
            }
        });

        jButton09.setText("9");
        jButton09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton09ActionPerformed(evt);
            }
        });

        jButtonMenos.setText("-");
        jButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosActionPerformed(evt);
            }
        });

        jButtonClear.setText("C");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButton00.setText("0");
        jButton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton00ActionPerformed(evt);
            }
        });

        jButtonPonto.setText(".");
        jButtonPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPontoActionPerformed(evt);
            }
        });

        jButtonDiv1.setText("\\");
            jButtonDiv1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonDiv1ActionPerformed(evt);
                }
            });

            jButtonPotencia.setText("^");
            jButtonPotencia.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonPotenciaActionPerformed(evt);
                }
            });

            jButtonRaiz.setText("√");
            jButtonRaiz.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonRaizActionPerformed(evt);
                }
            });

            jButtonAbreParenteses.setText("(");
            jButtonAbreParenteses.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonAbreParentesesActionPerformed(evt);
                }
            });

            jButtonFechaParenteses.setText(")");
            jButtonFechaParenteses.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonFechaParentesesActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton04, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton01, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton07, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton00, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton08, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton09, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonDiv1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonFechaParenteses, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jButton02, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton03, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jButton05, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton06, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAbreParenteses, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(36, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton03, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton04, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton05, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton06, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAbreParenteses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton08, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton07, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton09, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDiv1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonFechaParenteses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton00, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(52, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    public boolean conferencia(){
        char funsao[] = jTextFieldResultado.getText().toCharArray();
        if(!jTextFieldResultado.getText().equals("")&& funsao[funsao.length-1] != 'x' && funsao[funsao.length-1] != '/' && funsao[funsao.length-1] != '+' && funsao[funsao.length-1] != '-' && funsao[funsao.length-1] != '.' && funsao[funsao.length-1] != '^'){
            return(true);
        }else{
            return(false);
        }  
    }
    
    public String resolverParenteses(String expresao){
        
    }
    private void jButton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton02ActionPerformed
        // TODO add your handling code here:
        if(ContCaracAtual < 20 && ContCaracTotal < 60){
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "2");
        Atual += "2";
        ContCaracAtual++;
        ContCaracTotal++;
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButton02ActionPerformed

    private void jButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton01ActionPerformed
        // TODO add your handling code here:
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "1");
        if(ContCaracAtual < 20 && ContCaracTotal < 60){
        Atual += "1";
        ContCaracAtual++;
        ContCaracTotal++;
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButton01ActionPerformed

    private void jButton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton00ActionPerformed
        if(ContCaracAtual < 20 && ContCaracTotal < 60){
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "0");
        Atual += "0";
        ContCaracAtual++;
        ContCaracTotal++;
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButton00ActionPerformed

    private void jButtonPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPontoActionPerformed
        // TODO add your handling code here:
        if(ponto == false){
            jTextFieldResultado.setText(jTextFieldResultado.getText() + ".");
            Atual += ".";
            ponto = true;
            ContCaracAtual++;
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButtonPontoActionPerformed

    private void jButton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton03ActionPerformed
        // TODO add your handling code here:
        if(ContCaracAtual < 20 && ContCaracTotal < 60){
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "3");
        Atual += "3";
        ContCaracAtual++;
        ContCaracTotal++;
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButton03ActionPerformed

    private void jButton04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton04ActionPerformed
        // TODO add your handling code here:
        if(ContCaracAtual < 20 && ContCaracTotal < 60){
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "4");
        Atual += "4";
        ContCaracAtual++;
        ContCaracTotal++;
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButton04ActionPerformed

    private void jButton05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton05ActionPerformed
        // TODO add your handling code here:
       if(ContCaracAtual < 20 && ContCaracTotal < 60){
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "5");
        Atual += "5";
        ContCaracAtual++;
        ContCaracTotal++;
        }
       jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButton05ActionPerformed

    private void jButton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton06ActionPerformed
        // TODO add your handling code here:
        if(ContCaracAtual < 20 && ContCaracTotal < 60){
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "6");
        Atual += "6";
        ContCaracAtual++;
        ContCaracTotal++;
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButton06ActionPerformed

    private void jButton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton07ActionPerformed
        // TODO add your handling code here:
        if(ContCaracAtual < 20 && ContCaracTotal < 60){
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "7");
        Atual += "7";
        ContCaracAtual++;
        ContCaracTotal++;
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButton07ActionPerformed

    private void jButton08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton08ActionPerformed
        // TODO add your handling code here:
        if(ContCaracAtual < 20 && ContCaracTotal < 60){
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "8");
        Atual += "8";
        ContCaracAtual++;
        ContCaracTotal++;
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButton08ActionPerformed

    private void jButton09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton09ActionPerformed
        // TODO add your handling code here:
        if(ContCaracAtual < 20 && ContCaracTotal < 60){
        jTextFieldResultado.setText(jTextFieldResultado.getText() + "9");
        Atual += "9";
        ContCaracAtual++;
        ContCaracTotal++;
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButton09ActionPerformed

    private void jButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomaActionPerformed
            if(conferencia()){
                if(Atual.equals("")){
                    ponto = false;
                    jTextFieldResultado.setText(jTextFieldResultado.getText() + "+");
                }else{
                    vetor[indice] = Atual;
                    Atual = "";
                    indice ++;
                    ponto = false;
                    jTextFieldResultado.setText(jTextFieldResultado.getText() + "+");
                    ContCaracAtual = 0;
                    ContCaracTotal++;
                }
            }
            jTextFieldResultado.requestFocus();
        
    }//GEN-LAST:event_jButtonSomaActionPerformed

    private void jButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosActionPerformed
        // TODO add your handling code here:
        char funsao[] = jTextFieldResultado.getText().toCharArray();
        if(jTextFieldResultado.getText().equals("")|| funsao[funsao.length-1] == 'x' || funsao[funsao.length-1] == '/'|| Atual.equals("")){
            Atual = "-";
            jTextFieldResultado.setText(jTextFieldResultado.getText() + "-");
            ContCaracTotal++;
            ContCaracAtual++;
        }else{
            if(funsao[funsao.length-1] == '-' || funsao[funsao.length-1] == '.'){
                
            }else{
                vetor[indice] = Atual;
                indice ++;
                Atual = "-";
                ponto = false;
                jTextFieldResultado.setText(jTextFieldResultado.getText() + "-");
                ContCaracAtual = 0;
                ContCaracTotal++;
            }
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButtonMenosActionPerformed

    private void jButtonResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultadoActionPerformed
        // TODO add your handling code here:
        resultado = 0;
        if(!Atual.equals(".") && !Atual.equals("") && !Atual.equals("-.")){
            if(Atual.equals("-")){
                Atual += "1";
            }
            vetor[indice] = Atual;
            Atual = "";
            for(int i = indice; i > 0; i--){
                if(vetor[i].equals("p")){
                    vetor[i-1] = Math.pow(Float.parseFloat(vetor[i-1]),(Float.parseFloat(vetor[i+1]))) + "";
                    vetor[i+1] = "1";
                    vetor[i] = "x";
                    i += 1;
                }else{
                    if(vetor[i].equals("r")){
                        vetor[i+1] = Math.pow(Float.parseFloat(vetor[i+1]),(1/(Float.parseFloat(vetor[i-1])))) + "";
                        vetor[i-1] = "1";
                        vetor[i] = "x";
                        i += 1;
                    }
                }
            }    
            for( int i = 1; i < indice; i++){
                if(vetor[i].equals("x")){
                    vetor[i+1] = (Float.parseFloat(vetor[i-1])*(Float.parseFloat(vetor[i+1]))) + "";
                    vetor[i-1] = "0";
                    vetor[i] = "0";
                    i += 1;
                }else{
                    if(vetor[i].equals("d")){
                    vetor[i+1] = (Float.parseFloat(vetor[i-1])/(Float.parseFloat(vetor[i+1]))) + "";
                    vetor[i-1] = "0";
                    vetor[i] = "0";
                    i += 1;
                    }
                }
            }
            for( int i = 0; i <= indice; i++){
                resultado += Float.parseFloat(vetor[i]);
                vetor[i] = "";
            }
            Atual = resultado + "";
            ContCaracAtual = Atual.length();
            ContCaracTotal = ContCaracAtual;
            indice = 0;
            jTextFieldResultado.setText(resultado + "");
            ponto = true;
            }else{
                if(jTextFieldResultado.getText().equals("")){
                    //Caso não tenha nada escrito
                }else{
                    JOptionPane.showMessageDialog(null, "Revise a formatação");
                }
            }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButtonResultadoActionPerformed
    
    private void jButtonVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVezesActionPerformed
        // TODO add your handling code here:
        if(conferencia()){
            vetor[indice] = Atual;
            vetor[indice+1] = "x";
            indice += 2;
            jTextFieldResultado.setText(jTextFieldResultado.getText() + "x");
            Atual = "";
            ponto = false;
            ContCaracAtual = 0;
            ContCaracTotal++;
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButtonVezesActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i <= indice; i ++){
            vetor[i] = "";
        }
        ponto = false;
        indice = 0;
        resultado = 0;
        jTextFieldResultado.setText("");
        Atual = "";
        ContCaracAtual = 0;
        ContCaracTotal = 0;
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldResultado.getText().equals("")){
            char funsao[] = jTextFieldResultado.getText().toCharArray();
                if(funsao[funsao.length-1] == '+'){
                    for(int i = 0; i < funsao.length-1; i++){
                        BarraRes += funsao[i];
                    }
                    jTextFieldResultado.setText(BarraRes);
                    BarraRes = "";
                    ContCaracTotal--;
                }else{
                    if(funsao[funsao.length-1] == '.'){
                        ponto = false;
                     }
                    for(int i = 0; i < funsao.length-1; i++){
                        BarraRes += funsao[i];
                    }
                    jTextFieldResultado.setText(BarraRes);
                    BarraRes = "";
                    ContCaracTotal--;


                    if(Atual.equals("")){
                        indice--;
                        if(vetor[indice].equals("x") || vetor[indice].equals("d") || vetor[indice].equals("p") || vetor[indice].equals("r")){
                            vetor[indice] = "";
                            if(indice>0){
                                Atual = vetor[indice-1];
                                char funsaoAtual[] = Atual.toCharArray();
                                for(int i = 0; i < funsaoAtual.length-1; i++){
                                    if(funsaoAtual[i] == '.'){
                                        ponto = true;
                                    }
                                }
                                
                            }
                            Atual = "";
                        }else{
                            Atual = vetor[indice];
                            char funsaoAtual[] = Atual.toCharArray();
                            ContCaracAtual = funsaoAtual.length-1;
                            for(int i = 0; i < funsaoAtual.length-1; i++){
                                BarraRes += funsaoAtual[i];
                            }
                            Atual = BarraRes;
                            BarraRes = "";
                            vetor[indice] = "";
                        }
                    }else{
                        char funsaoAtual[] = Atual.toCharArray();
                        for(int i = 0; i < funsaoAtual.length-1; i++){
                            BarraRes += funsaoAtual[i];
                        }
                        Atual = BarraRes;
                        BarraRes = "";
                        ContCaracAtual--;
                    }
                }
            
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonDiv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiv1ActionPerformed
        // TODO add your handling code here:
        if(conferencia()){
            vetor[indice] = Atual;
            vetor[indice+1] = "d";
            indice += 2;
            jTextFieldResultado.setText(jTextFieldResultado.getText() + "/");
            Atual = "";
            ponto = false;
            ContCaracAtual = 0;
            ContCaracTotal++;
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButtonDiv1ActionPerformed

    private void jButtonPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPotenciaActionPerformed
        // TODO add your handling code here:
        if(conferencia()){
            vetor[indice] = Atual;
            vetor[indice+1] = "p";
            indice += 2;
            jTextFieldResultado.setText(jTextFieldResultado.getText() + "^");
            Atual = "";
            ponto = false;
            ContCaracAtual = 0;
            ContCaracTotal++;
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButtonPotenciaActionPerformed

    private void jButtonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRaizActionPerformed
        // TODO add your handling code here:
        if(!conferencia()) jButton02.doClick();
        if(conferencia()){
            vetor[indice] = Atual;
            vetor[indice+1] = "r";
            indice += 2;
            jTextFieldResultado.setText(jTextFieldResultado.getText() + "√");
            Atual = "";
            ponto = false;
            ContCaracAtual = 0;
            ContCaracTotal++;
        }
        jTextFieldResultado.requestFocus();
    }//GEN-LAST:event_jButtonRaizActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
           
    }//GEN-LAST:event_formKeyTyped

    private void jTextFieldResultadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldResultadoKeyTyped
        char e = evt.getKeyChar();
        switch(e){
            case '0' :
                jButton00.doClick();
                break;
            case '1' :
                jButton01.doClick();
                break;
            case '2' :
                jButton02.doClick();
                break;
            case '3' :
                jButton03.doClick();
                break;
            case '4' :
                jButton04.doClick();
                break;
            case '5' :
                jButton05.doClick();
                break;
            case '6' :
                jButton06.doClick();
                break;
            case '7' :
                jButton07.doClick();
                break;
            case '8' :
                jButton08.doClick();
                break;
            case '9' :
                jButton09.doClick();
                break;
            case '+' :
                jButtonSoma.doClick();
                break;
            case '-' :
                jButtonMenos.doClick();
                break;
            case 'x':
                jButtonVezes.doClick();
                break;
            case '*' : 
                jButtonVezes.doClick();
                break;
            case '/' :
                jButtonDiv1.doClick();
                break;
            case '^':
                jButtonPotencia.doClick();
                break;
            case ',' :
                jButtonPonto.doClick();
                break;
            case '.' :
                jButtonPonto.doClick();
                break;
            case 'r':
                jButtonRaiz.doClick();
                break;
        }
    }//GEN-LAST:event_jTextFieldResultadoKeyTyped

    private void jTextFieldResultadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldResultadoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE){
            jButtonApagar.doClick();
        }else{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                jButtonResultado.doClick();
            }else{
                if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
                    jButtonClear.doClick();
                }
            }
        }
        
    }//GEN-LAST:event_jTextFieldResultadoKeyPressed

    private void jButtonAbreParentesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbreParentesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAbreParentesesActionPerformed

    private void jButtonResultado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonResultado2ActionPerformed

    private void jButtonFechaParentesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFechaParentesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFechaParentesesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton00;
    private javax.swing.JButton jButton01;
    private javax.swing.JButton jButton02;
    private javax.swing.JButton jButton03;
    private javax.swing.JButton jButton04;
    private javax.swing.JButton jButton05;
    private javax.swing.JButton jButton06;
    private javax.swing.JButton jButton07;
    private javax.swing.JButton jButton08;
    private javax.swing.JButton jButton09;
    private javax.swing.JButton jButtonAbreParenteses;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDiv1;
    private javax.swing.JButton jButtonFechaParenteses;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonPonto;
    private javax.swing.JButton jButtonPotencia;
    private javax.swing.JButton jButtonRaiz;
    private javax.swing.JButton jButtonResultado;
    private javax.swing.JButton jButtonResultado2;
    private javax.swing.JButton jButtonSoma;
    private javax.swing.JButton jButtonVezes;
    private javax.swing.JTextField jTextFieldResultado;
    // End of variables declaration//GEN-END:variables
}
